import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const exercises = [
  {
    name: 'Barbell Back Squat',
    slug: 'barbell-back-squat',
    description: 'The king of lower body exercises, targeting quads, glutes, and hamstrings.',
    instructions: '1. Position barbell on upper back\n2. Stand with feet shoulder-width apart\n3. Descend by bending knees and hips\n4. Keep chest up and back straight\n5. Drive through heels to stand',
    muscleGroup: 'legs',
    secondaryMuscles: JSON.stringify(['glutes', 'hamstrings', 'core']),
    equipment: 'barbell',
    difficulty: 'intermediate',
    isCompound: true,
  },
  {
    name: 'Bench Press',
    slug: 'bench-press',
    description: 'Primary chest builder targeting pectorals, anterior deltoids, and triceps.',
    instructions: '1. Lie on bench with eyes under the bar\n2. Grip bar slightly wider than shoulder width\n3. Unrack and lower to mid-chest\n4. Press up to lockout\n5. Keep shoulder blades retracted',
    muscleGroup: 'chest',
    secondaryMuscles: JSON.stringify(['shoulders', 'triceps']),
    equipment: 'barbell',
    difficulty: 'intermediate',
    isCompound: true,
  },
  {
    name: 'Deadlift',
    slug: 'deadlift',
    description: 'Full posterior chain exercise targeting back, glutes, hamstrings, and grip.',
    instructions: '1. Stand with feet hip-width apart\n2. Grip bar outside knees\n3. Keep back flat, chest up\n4. Drive through heels\n5. Lock out hips at top',
    muscleGroup: 'back',
    secondaryMuscles: JSON.stringify(['glutes', 'hamstrings', 'core', 'forearms']),
    equipment: 'barbell',
    difficulty: 'intermediate',
    isCompound: true,
  },
  {
    name: 'Pull-Up',
    slug: 'pull-up',
    description: 'Fundamental upper body pulling movement for lat development.',
    instructions: '1. Hang from bar with overhand grip\n2. Pull chest toward bar\n3. Squeeze shoulder blades\n4. Lower with control\n5. Full extension at bottom',
    muscleGroup: 'back',
    secondaryMuscles: JSON.stringify(['biceps', 'forearms', 'core']),
    equipment: 'pull-up bar',
    difficulty: 'intermediate',
    isCompound: true,
  },
  {
    name: 'Overhead Press',
    slug: 'overhead-press',
    description: 'Primary shoulder mass builder and overhead strength exercise.',
    instructions: '1. Clean bar to shoulders\n2. Brace core\n3. Press bar overhead\n4. Lock out at top\n5. Lower with control',
    muscleGroup: 'shoulders',
    secondaryMuscles: JSON.stringify(['triceps', 'core']),
    equipment: 'barbell',
    difficulty: 'intermediate',
    isCompound: true,
  },
  {
    name: 'Barbell Row',
    slug: 'barbell-row',
    description: 'Fundamental back thickness builder.',
    instructions: '1. Hinge at hips with flat back\n2. Grip bar shoulder width\n3. Pull to lower chest\n4. Squeeze shoulder blades\n5. Lower with control',
    muscleGroup: 'back',
    secondaryMuscles: JSON.stringify(['biceps', 'rear deltoids']),
    equipment: 'barbell',
    difficulty: 'intermediate',
    isCompound: true,
  },
  {
    name: 'Romanian Deadlift',
    slug: 'romanian-deadlift',
    description: 'Hamstring and glute focused hip hinge movement.',
    instructions: '1. Hold bar at hip level\n2. Push hips back\n3. Lower bar along thighs\n4. Feel stretch in hamstrings\n5. Drive hips forward to stand',
    muscleGroup: 'legs',
    secondaryMuscles: JSON.stringify(['glutes', 'lower back']),
    equipment: 'barbell',
    difficulty: 'intermediate',
    isCompound: true,
  },
  {
    name: 'Leg Press',
    slug: 'leg-press',
    description: 'Machine-based quad and glute builder.',
    instructions: '1. Position feet shoulder-width on platform\n2. Release safety and lower\n3. Descend until 90 degree knee angle\n4. Press through heels\n5. Do not lock out knees',
    muscleGroup: 'legs',
    secondaryMuscles: JSON.stringify(['glutes', 'hamstrings']),
    equipment: 'leg press machine',
    difficulty: 'beginner',
    isCompound: true,
  },
  {
    name: 'Dumbbell Lateral Raise',
    slug: 'dumbbell-lateral-raise',
    description: 'Isolation exercise for medial deltoid.',
    instructions: '1. Hold dumbbells at sides\n2. Raise arms to shoulder level\n3. Lead with elbows\n4. Slight bend in elbows\n5. Lower with control',
    muscleGroup: 'shoulders',
    secondaryMuscles: JSON.stringify([]),
    equipment: 'dumbbells',
    difficulty: 'beginner',
    isIsolation: true,
  },
  {
    name: 'Bicep Curl',
    slug: 'bicep-curl',
    description: 'Classic isolation exercise for bicep peak.',
    instructions: '1. Stand with dumbbells at sides\n2. Curl weights toward shoulders\n3. Keep elbows stationary\n4. Squeeze at top\n5. Lower with control',
    muscleGroup: 'arms',
    secondaryMuscles: JSON.stringify(['forearms']),
    equipment: 'dumbbells',
    difficulty: 'beginner',
    isIsolation: true,
  },
  {
    name: 'Tricep Pushdown',
    slug: 'tricep-pushdown',
    description: 'Cable isolation exercise for tricep development.',
    instructions: '1. Face cable machine\n2. Grip bar or rope\n3. Push down until arms straight\n4. Keep elbows pinned\n5. Squeeze triceps at bottom',
    muscleGroup: 'arms',
    secondaryMuscles: JSON.stringify([]),
    equipment: 'cable machine',
    difficulty: 'beginner',
    isIsolation: true,
  },
  {
    name: 'Leg Curl',
    slug: 'leg-curl',
    description: 'Isolation exercise for hamstring development.',
    instructions: '1. Lie face down on machine\n2. Position pad above heels\n3. Curl toward glutes\n4. Squeeze at top\n5. Lower with control',
    muscleGroup: 'legs',
    secondaryMuscles: JSON.stringify([]),
    equipment: 'leg curl machine',
    difficulty: 'beginner',
    isIsolation: true,
  },
  {
    name: 'Leg Extension',
    slug: 'leg-extension',
    description: 'Isolation exercise for quad development.',
    instructions: '1. Sit in machine with pad on ankles\n2. Extend legs until straight\n3. Squeeze quads at top\n4. Do not lock knees\n5. Lower with control',
    muscleGroup: 'legs',
    secondaryMuscles: JSON.stringify([]),
    equipment: 'leg extension machine',
    difficulty: 'beginner',
    isIsolation: true,
  },
  {
    name: 'Incline Dumbbell Press',
    slug: 'incline-dumbbell-press',
    description: 'Upper chest focused pressing movement.',
    instructions: '1. Set bench to 30-45 degrees\n2. Hold dumbbells at chest\n3. Press up and together\n4. Squeeze at top\n5. Lower with control',
    muscleGroup: 'chest',
    secondaryMuscles: JSON.stringify(['shoulders', 'triceps']),
    equipment: 'dumbbells',
    difficulty: 'intermediate',
    isCompound: true,
  },
  {
    name: 'Cable Fly',
    slug: 'cable-fly',
    description: 'Chest isolation movement for stretch and squeeze.',
    instructions: '1. Stand between cable stations\n2. Grip handles with slight elbow bend\n3. Bring hands together at chest\n4. Feel chest squeeze\n5. Return with control',
    muscleGroup: 'chest',
    secondaryMuscles: JSON.stringify([]),
    equipment: 'cable machine',
    difficulty: 'intermediate',
    isIsolation: true,
  },
  {
    name: 'Lat Pulldown',
    slug: 'lat-pulldown',
    description: 'Machine-based alternative to pull-ups.',
    instructions: '1. Sit with thighs under pads\n2. Grip bar wide and overhand\n3. Pull to upper chest\n4. Lean back slightly\n5. Control the return',
    muscleGroup: 'back',
    secondaryMuscles: JSON.stringify(['biceps', 'rear deltoids']),
    equipment: 'lat pulldown machine',
    difficulty: 'beginner',
    isCompound: true,
  },
  {
    name: 'Face Pull',
    slug: 'face-pull',
    description: 'Rear delt and upper back exercise for shoulder health.',
    instructions: '1. Set cable at face height\n2. Grip rope with thumbs up\n3. Pull to face level\n4. Spread rope ends apart\n5. Squeeze rear delts',
    muscleGroup: 'shoulders',
    secondaryMuscles: JSON.stringify(['upper back', 'rotator cuff']),
    equipment: 'cable machine',
    difficulty: 'beginner',
    isIsolation: true,
  },
  {
    name: 'Calf Raise',
    slug: 'calf-raise',
    description: 'Isolation exercise for calf development.',
    instructions: '1. Stand on elevated surface\n2. Position balls of feet on edge\n3. Lower heels below platform\n4. Rise onto toes\n5. Squeeze at top',
    muscleGroup: 'legs',
    secondaryMuscles: JSON.stringify([]),
    equipment: 'calf raise machine',
    difficulty: 'beginner',
    isIsolation: true,
  },
  {
    name: 'Plank',
    slug: 'plank',
    description: 'Core stability exercise for overall core strength.',
    instructions: '1. Position on forearms and toes\n2. Keep body in straight line\n3. Engage core and glutes\n4. Do not let hips sag\n5. Hold for prescribed time',
    muscleGroup: 'core',
    secondaryMuscles: JSON.stringify(['shoulders']),
    equipment: 'bodyweight',
    difficulty: 'beginner',
    isIsolation: true,
  },
  {
    name: 'Treadmill Run',
    slug: 'treadmill-run',
    description: 'Cardiovascular conditioning exercise.',
    instructions: '1. Set desired speed and incline\n2. Maintain upright posture\n3. Land mid-foot\n4. Swing arms naturally\n5. Cool down with walking',
    muscleGroup: 'cardio',
    secondaryMuscles: JSON.stringify(['legs']),
    equipment: 'treadmill',
    difficulty: 'beginner',
    isCardio: true,
  },
  {
    name: 'Dumbbell Lunges',
    slug: 'dumbbell-lunges',
    description: 'Unilateral leg exercise for strength and balance.',
    instructions: '1. Hold dumbbells at sides\n2. Step forward into lunge\n3. Lower until back knee nearly touches floor\n4. Drive through front heel\n5. Alternate legs',
    muscleGroup: 'legs',
    secondaryMuscles: JSON.stringify(['glutes', 'core']),
    equipment: 'dumbbells',
    difficulty: 'intermediate',
    isCompound: true,
  },
  {
    name: 'Hammer Curl',
    slug: 'hammer-curl',
    description: 'Bicep curl variation targeting brachialis.',
    instructions: '1. Hold dumbbells with neutral grip\n2. Curl weights toward shoulders\n3. Keep palms facing each other\n4. Squeeze at top\n5. Lower with control',
    muscleGroup: 'arms',
    secondaryMuscles: JSON.stringify(['forearms']),
    equipment: 'dumbbells',
    difficulty: 'beginner',
    isIsolation: true,
  },
  {
    name: 'Chest Dips',
    slug: 'chest-dips',
    description: 'Bodyweight compound movement for chest and triceps.',
    instructions: '1. Grip parallel bars\n2. Lean forward for chest focus\n3. Lower until stretch in chest\n4. Press back up\n5. Keep elbows tracking out',
    muscleGroup: 'chest',
    secondaryMuscles: JSON.stringify(['triceps', 'shoulders']),
    equipment: 'dip bars',
    difficulty: 'intermediate',
    isCompound: true,
  },
  {
    name: 'Seated Cable Row',
    slug: 'seated-cable-row',
    description: 'Cable back exercise for thickness and pull strength.',
    instructions: '1. Sit with feet on platform\n2. Grip handle with arms extended\n3. Pull to lower chest\n4. Squeeze shoulder blades\n5. Extend with control',
    muscleGroup: 'back',
    secondaryMuscles: JSON.stringify(['biceps', 'rear deltoids']),
    equipment: 'cable machine',
    difficulty: 'beginner',
    isCompound: true,
  },
];

async function main() {
  console.log('Starting seed...');

  for (const exercise of exercises) {
    await prisma.exercise.upsert({
      where: { slug: exercise.slug },
      update: exercise,
      create: exercise,
    });
    console.log(`Upserted: ${exercise.name}`);
  }

  console.log(`\nSeeded ${exercises.length} exercises.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
